LibraryManagementMVC/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using LibraryManagementService.HttpClients;
using LibraryManagement.ViewModel;
using Microsoft.AspNetCore.Mvc;
using LibraryManagement.Models;
using Microsoft.AspNetCore.Authorization;

namespace LibraryManagementMVC.Controllers
{
    [Authorize]
    public class AuthorsController : Controller
    {
        
        private readonly HttpClientAuthorsAPI _http;

        public AuthorsController(HttpClientAuthorsAPI httpApi)
        {
            _http = httpApi;
        }

        private BookView ConvertBook(Book b)
        {
            var authorView = new List<AuthorView>();
            foreach (var a in b.BooksAuthors)
            {
                authorView.Add(Convert(a.Author));
            }
            var bookView = new BookView()
            {
                Id = b.Id,
                Title = b.Title,
                ISBN = b.ISBN,
                Year = b.Year,
                Authors = authorView,
            };
            return bookView;
        }
        private AuthorView Convert(Author a)
        {
            var authorView = new AuthorView()
            {
                Name = a.Name,
                LastName = a.LastName,
                BirthDay = a.BirthDay,
                Email = a.Email,
                Id = a.Id,
            };
            return authorView;
        }
        // GET: AuthorsController
        public async Task<ActionResult> Index()
        {
            var authors = await _http.GetAll();
            var authorsView = new List<AuthorView>();
            if (authors != null)
            {
                foreach (var a in authors)
                {
                    authorsView.Add(Convert(a));
                }
            }
            return View(authorsView);
        }

        // GET: AuthorsController/Details/5
        public async Task<ActionResult> Details(Guid id)
        {
            var author = await _http.Get(id);
            var authorView = Convert(author);
            return View(authorView);
        }

        // GET: AuthorsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AuthorsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Author a)
        {
            try
            {
                var author = await _http.Create(a);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AuthorsController/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            var author = await _http.Get(id);
            var authorView = Convert(author);
            return View(authorView);
        }

        // POST: AuthorsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Author author)
        {
            try
            {
                var a = await _http.Update(author);
                var authorView = Convert(a);
                return RedirectToAction(nameof(Details), new { id = authorView.Id });
            }
            catch
            {
                return View();
            }
        }

        // GET: AuthorsController/Delete/5
        public async Task<ActionResult> Delete(Guid id)
        {
            var a = await _http.Get(id);
            var authorView = Convert(a);
            return View(authorView);
        }

        // POST: AuthorsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(AuthorView author)
        {
            try
            {
                await _http.Delete(author.Id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LibraryManagementMVC/Controllers/BooksController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using LibraryManagement.Models;
using LibraryManagement.ViewModel;
using LibraryManagementService.HttpClients;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementMVC.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
        private readonly HttpClientBookAPI _http;
        private readonly HttpClientAuthorsAPI _httpAuthor;
        private IMapper _mapper;

        public BooksController(HttpClientBookAPI httpApi, HttpClientAuthorsAPI httpAuthor, IMapper mapper)
        {
            _http = httpApi;
            _httpAuthor = httpAuthor;
            _mapper = mapper;
        }
        private AuthorView Convert(Author a)
        {
            var authorView = new AuthorView()
            {
                Name = a.Name,
                LastName = a.LastName,
                BirthDay = a.BirthDay,
                Email = a.Email,
                Id = a.Id,
            };
            return authorView;
        }
        private BookView ConvertBook(Book b)
        {
            var authorView = new List<AuthorView>();
           
                foreach (var a in b.BooksAuthors)
                {
                    authorView.Add(Convert(a.Author));
                }
            
            var bookView = new BookView()
            {
                Id = b.Id,
                Title = b.Title,
                ISBN = b.ISBN,
                Year = b.Year,
                Authors = authorView,
            };
            return bookView;
        }
        private Book ConvertBook(BookView b)
        {
            var authorView = new List<Guid>();
            var bookAuthors = new List<BookAuthor>();

            foreach (var a in b.Authors)
            {
                var BA = new BookAuthor()
                {
                    AuthorId = a.Id,
                };
                bookAuthors.Add(BA);
            }

            var book = new Book()
            {
                Id = b.Id,
                Title = b.Title,
                ISBN = b.ISBN,
                Year = (int)b.Year,
                BooksAuthors = bookAuthors,
            };

            return book;
        }
        public async Task<ActionResult> Index()
        {
            var books = await _http.GetAll();
            var booksView = new List<BookView>();
            if (books != null)
            {
                foreach (var b in books)
                {
                    booksView.Add(ConvertBook(b));
                }
            }
            return View(booksView);
        }
        public async Task<ActionResult> Details(Guid id)
        {
            var book = await _http.Get(id);
            var bookView = ConvertBook(book);
            return View(bookView);
        }
        public async Task<ActionResult> Create()
        {
            var authors = await _httpAuthor.GetAll();
            var authosView = new List<AuthorView>();
            foreach (var a in authors)
            {
                authosView.Add(Convert(a));
            }
            var bookView = new BookView()
            {
                Year = null,
                Authors = authosView,
            };
            return View(bookView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([FromForm] string title, string ISBN, int year, IEnumerable<string> Authors)
        {
            var authors = new List<AuthorView>();

            foreach (var id in Authors)
            {
                var a = await _httpAuthor.Get(Guid.Parse(id));
                var av = Convert(a);
                if (a != null)
                {
                    authors.Add(av);
                }
            }
            var bv = new BookView()
            {
                Title = title,
                ISBN = ISBN,
                Year = year,
                Authors = authors,
            };
            try
            {
                var author = await _http.Create(ConvertBook(bv));
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<ActionResult> Edit(Guid id)
        {
            var book = await _http.Get(id);
            var bookView = ConvertBook(book);
            var authors = await _httpAuthor.GetAll();
            var authosView = new List<AuthorView>();
            foreach (var a in authors)
            {
                var aView = Convert(a);
                foreach (var au in bookView.Authors)
                {
                    if (aView.Id == au.Id)
                    {
                        aView.Select = true;
                    }
                }
                authosView.Add(aView);
            }
            bookView.Authors = authosView;
            return View(bookView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([FromForm] Guid Id, string title, string ISBN, int year, IEnumerable<string> Authors)
        {
            var authors = new List<AuthorView>();

            foreach (var id in Authors)
            {
                var a = await _httpAuthor.Get(Guid.Parse(id));
                var av = Convert(a);
                if (a != null)
                {
                    authors.Add(av);
                }
            }
            var bv = new BookView()
            {
                Id = Id,
                Title = title,
                ISBN = ISBN,
                Year = year,
                Authors = authors,
            };
            try
            {
                var sendbook = ConvertBook(bv);
                var a = await _http.Update(sendbook);
                return RedirectToAction(nameof(Details), new { id = a.Id });
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> Delete(Guid id)
        {
            var book = await _http.Get(id);
            var bookView = ConvertBook(book);
            return View(bookView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(BookView book)
        {
            try
            {
                await _http.Delete(book.Id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LibraryManagementMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryManagementMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryManagementMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authors" asp-action="Index">Authors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - LibraryManagementMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LibraryManagementMVC/Views/Shared/_ScriptsMunitinho.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.2/bootstrap3-typeahead.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css" />

<script>
    $(document).ready(function () {
        $('#authors').multiselect({
            nonSelectedText: 'Select Authors',
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true,
            buttonWidth: '400px'
        });
    });
</script>